<?php 
	include('init.php'); // INCLUDE INITIATE FILE WHICH HAVE ALL FUNCTIONS FILES..
	$Object = new Pet(); // CALL CLASS BY OBJECT OF CLASS...
	$Result = $Object->profile($_GET['pid']); // ASSIGN CLASS DATA TO OBJECT...
	$row = $Result['data']->fetch_assoc();
	
	include('./header.php'); // INCLUDE HEADER FILE...	
	include('html/profile.html'); // INCLUDE HTML FILE...
	include('./footer.php'); // INCLUDE FOOTER FILE...
	
?>